eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/
spring:
  application:
    name: spring-eureka-client
server:
  port: 8003
feign:
  hystrix:
    enabled: true
#spring boot 2.0新增配置
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      base-path: /